version: "3.8"

services:
  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters
  
  payment_gateway:
    container_name: payment_gateway
    build:
      context: .
      dockerfile: src/PaymentGateway.Api/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1000M
    environment:
      - ASPNETCORE_URLS=http://*:5000/
      - ASPNETCORE_ENVIRONMENT=Development
      - Acquirer:Uri=http://bank_simulator:8080/payments
    ports:
      - "5000:5000"
